# Generated by Django 3.0.3 on 2020-02-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stock',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
